-- Create and populate our products using a single insert with many rows
CREATE TABLE products
(
    id          NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 101) NOT NULL PRIMARY KEY,
    name        VARCHAR2(255) NOT NULL,
    description VARCHAR2(512),
    weight      FLOAT
);
GRANT SELECT ON products to c##dbzuser;
ALTER TABLE products
    ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;


-- Create and populate the products on hand using multiple inserts
CREATE TABLE products_on_hand
(
    product_id NUMBER(4) NOT NULL PRIMARY KEY,
    quantity   NUMBER(4) NOT NULL,
    FOREIGN KEY (product_id) REFERENCES products (id)
);
GRANT SELECT ON products_on_hand to c##dbzuser;
ALTER TABLE products_on_hand
    ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Create some customers ...
CREATE TABLE customers
(
    id         NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1001) NOT NULL PRIMARY KEY,
    first_name VARCHAR2(255) NOT NULL,
    last_name  VARCHAR2(255) NOT NULL,
    email      VARCHAR2(255) NOT NULL UNIQUE
);
GRANT SELECT ON customers to c##dbzuser;
ALTER TABLE customers
    ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;


-- Create some very simple orders
CREATE TABLE debezium.orders
(
    id         NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 10001) NOT NULL PRIMARY KEY,
    order_date DATE NOT NULL,
    purchaser  NUMBER(4) NOT NULL,
    quantity   NUMBER(4) NOT NULL,
    product_id NUMBER(4) NOT NULL,
    FOREIGN KEY (purchaser) REFERENCES customers (id),
    FOREIGN KEY (product_id) REFERENCES products (id)
);
GRANT SELECT ON orders to c##dbzuser;
ALTER TABLE orders
    ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;


