-- ============================================
-- TABLA: CATEGORIA
-- ============================================
CREATE TABLE DEBEZIUM.CATEGORIA
(
    id NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(500),
    fecha_creacion DATE
);
GRANT SELECT ON DEBEZIUM.CATEGORIA TO c##dbzuser;
ALTER TABLE DEBEZIUM.CATEGORIA ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- ============================================
-- TABLA: AUTOR
-- ============================================
CREATE TABLE DEBEZIUM.AUTOR
(
    id NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    fecha_nacimiento DATE,
    nacionalidad VARCHAR2(50),
    fecha_creacion DATE
);
GRANT SELECT ON DEBEZIUM.AUTOR TO c##dbzuser;
ALTER TABLE DEBEZIUM.AUTOR ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- ============================================
-- TABLA: LIBRO
-- ============================================
CREATE TABLE DEBEZIUM.LIBRO
(
    id NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    isbn VARCHAR2(20) UNIQUE NOT NULL,
    titulo VARCHAR2(255) NOT NULL,
    id_autor NUMBER(6) NOT NULL,
    id_categoria NUMBER(6) NOT NULL,
    editorial VARCHAR2(100),
    fecha_publicacion DATE,
    edicion NUMBER(6),
    numero_paginas NUMBER(6),
    estado VARCHAR2(20),
    ubicacion VARCHAR2(100),
    fecha_creacion DATE,
    CONSTRAINT fk_libro_autor FOREIGN KEY (id_autor) REFERENCES DEBEZIUM.AUTOR(id),
    CONSTRAINT fk_libro_categoria FOREIGN KEY (id_categoria) REFERENCES DEBEZIUM.CATEGORIA(id)
);
GRANT SELECT ON DEBEZIUM.LIBRO TO c##dbzuser;
ALTER TABLE DEBEZIUM.LIBRO ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- ============================================
-- TABLA: USUARIO
-- ============================================
CREATE TABLE DEBEZIUM.USUARIO
(
    id NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    numero_identificacion VARCHAR2(20) UNIQUE NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    telefono VARCHAR2(15),
    direccion VARCHAR2(255),
    tipo_usuario VARCHAR2(20),
    estado VARCHAR2(15),
    fecha_registro DATE,
    fecha_actualizacion DATE
);
GRANT SELECT ON DEBEZIUM.USUARIO TO c##dbzuser;
ALTER TABLE DEBEZIUM.USUARIO ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- ============================================
-- TABLA: PRESTAMO
-- ============================================
CREATE TABLE DEBEZIUM.PRESTAMO
(
    id NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    id_libro NUMBER(6) NOT NULL,
    id_usuario NUMBER(6) NOT NULL,
    fecha_prestamo DATE NOT NULL,
    fecha_devolucion_prevista DATE NOT NULL,
    fecha_devolucion_real DATE,
    estado VARCHAR2(20),
    multa NUMBER(10,2),
    observaciones VARCHAR2(500),
    fecha_creacion DATE,
    CONSTRAINT fk_prestamo_libro FOREIGN KEY (id_libro) REFERENCES DEBEZIUM.LIBRO(id),
    CONSTRAINT fk_prestamo_usuario FOREIGN KEY (id_usuario) REFERENCES DEBEZIUM.USUARIO(id)
);
GRANT SELECT ON DEBEZIUM.PRESTAMO TO c##dbzuser;
ALTER TABLE DEBEZIUM.PRESTAMO ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

exit;
